server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.28.94.53:3306/khala?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: oscroll123

mybatis:
  #实体类所做包
  type-aliases-package: com.oscroll.domain
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml

management:
  server:
    port: 10212
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true #启用shutdown端点
